# Generated by Django 5.0.6 on 2024-07-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
