# Generated by Django 5.0.6 on 2024-07-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='name1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
