# Generated by Django 5.0.6 on 2024-07-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_contact_name_contact_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name1',
            new_name='name',
        ),
    ]
