# Generated by Django 5.0.6 on 2024-07-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_name1_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menue',
            old_name='name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='cname',
        ),
    ]
